ciesga_currilos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings	
from django.conf.urls.static import static
from core import urls

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('candidato/', include('candidato.urls', namespace="candidato")),
    path('empregador/', include('empregador.urls', namespace="empregador")),
    path('vagas/', include('vagas.urls', namespace="vagas")),
    path('captcha/', include('captcha.urls')),
    
    
    #path('municipios_app/', include('municipios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path("", views.home, name='home'),
    path('contato', views.contact, name='contact'),
    path('saiba-mais', views.saiba_mais, name='saiba_mais')
]

usuario/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name='usuario'

urlpatterns = [
    path("password_reset", views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<key>', views.password_reset_confirm, 
        name='password_reset_confirm'),
    path('editar-senha/', views.edit_password,  name='edit_password'),
    path('login/', LoginView.as_view(template_name = 'login.html'), 
    	 name='login'),
    path('logout/', LogoutView.as_view(next_page= 'core:home'), 
    	 name='logout'),
    path('cadastre-se_candidato/', views.register, name='register'),
    path('cadastre-se_empregador/', views.register_empregador, name='register_empregador'),
    path('painel/', views.dashboard, name='dashboard'),
    path('teste/', views.choice_register, name='choice_register'),
]

usuario/models.py
from django.db import models
import re
import datetime
from django.core import validators
from django.conf import settings
from core.choices import *
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.contrib.auth.validators import UnicodeUsernameValidator

class User(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        'Usuário', max_length=30, unique=True, validators=[username_validator],
    )
    name = models.CharField('Nome Completo', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    user_type = models.CharField( 
    		'Tipo de Usuário',
			max_length=25,
			blank=False,
			choices=USER_TYPE,
		)			
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuario',
        #related_name='resets',
        on_delete=models.CASCADE,
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User
from candidato.models import *
from empregador.models import *

from core.utils import generate_hash_key
from core.mail import send_mail_template

from .models import PasswordReset
from django.contrib.localflavor.br.forms import BRCPFField,BRCNPJField
#from captcha.fields import CaptchaField


User = get_user_model()


class RegisterForm(forms.ModelForm):

    cpf = BRCPFField(label = 'CPF',max_length = 14 , min_length = 11)
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )
    #captcha = CaptchaField()
    
    def clean_cpf(self):
        cpf=self.cleaned_data['cpf']
        if Candidato.objects.filter(cpf=cpf).exists():
            raise forms.ValidationError('CPF já cadastrado')
        return cpf

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):    
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.user_type = "Candidato"
        if commit:
            user.save()
            candidato = Candidato()
            candidato.user_id = user.id
            candidato.cpf = self.cleaned_data['cpf']
            candidato.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

class Register_EmpregadorForm(forms.ModelForm):

    cnpj = BRCNPJField(label = 'CNPJ',max_length = 18 , min_length = 14)
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )
    #captcha = CaptchaField()
    
    def clean_cpf(self):
        cpf=self.cleaned_data['cpf']
        if Candidato.objects.filter(cpf=cpf).exists():
            raise forms.ValidationError('CPF já cadastrado')
        return cpf

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):    
        user = super(Register_EmpregadorForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.user_type = "Empregador"
        if commit:
            user.save()
            empregado = Empregador()
            empregado.user_id = user.id
            empregado.cnpj = self.cleaned_data['cnpj']
            empregado.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

        
class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário encontrado com este e-mail'
        )

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'password_reset_mail.html'
        subject = 'Criar nova senha no Portal CIESGA'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

class UserForm(forms.ModelForm):
    
    class Meta: 
        model = User
        fields = ['username', 'email', 'name', 'user_type','is_active', 'is_staff']

usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm,
    SetPasswordForm)
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages

from core.utils import generate_hash_key

from .forms import RegisterForm, PasswordResetForm, Register_EmpregadorForm
from .models import PasswordReset, User

User = get_user_model()

# Create your views here.
def register(request):
    template_name = 'register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('usuario:dashboard')
    else:
        form = RegisterForm()

    context = {
        'form': form,

    }
    return render(request, template_name, context)

def register_empregador(request):
    template_name = 'register_empregador.html'
    context = {}
    if request.method == 'POST':
        form = Register_EmpregadorForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('usuario:dashboard')
    else:
        form = Register_EmpregadorForm()

    context = {
        'form': form,

    }
    return render(request, template_name, context)

    
def password_reset(request):
    template_name = 'password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def dashboard(request):
    
    user=request.user 
    if user.user_type == 'Candidato':
        template_name = 'dashboard_candidato.html'
        context = {}
        return render(request, template_name, context)
    else :
        template_name = 'dashboard_empregador.html'
        context = {}
        return render(request, template_name, context)


@login_required
def edit_password(request):

    user = request.user
    if user.user_type == 'Candidato':
        template_name = 'edit_password.html'
    else:
        template_name = 'edit_password_empregador.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

def choice_register(request):
   return render(request, 'choice_register.html')

usuario/templates/choice_register.html
{% extends "base.html" %}

{% block content %}


    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Escolha abaixo o tipo de conta você dejesa criar:
                </h1>
                    <a href="{% url 'usuario:register' %}" class="pure-button-primary primary-button">Candidato</a>
                    <a href="{% url 'usuario:register_empregador' %}" class="pure-button-primary primary-button">Empresa</a>
             </div>


               
             
{% endblock %}

usuario/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'usuario:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-4">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo, {{ user.username }}
                </li>
                {% block menu_options %}

                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}

            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

usuario/templates/edit_password.html
{% extends "dashboard_candidato.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'usuario:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

usuario/templates/edit_password_empregador.html
{% extends "dashboard_empregador.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'usuario:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

usuario/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'usuario:choice_register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="{% url 'usuario:password_reset' %}" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

usuario/templates/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviando para você com mais detalhes de como criar uma nova senha</p>
        {% else %}
        <h2>Informe seu E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

usuario/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

usuario/templates/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link: <a href="http://192.168.21.171:8000{% url 'usuario:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">Criar Nova Senha</a></p>

usuario/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <li>*IMPORTANTE* Apenas candidatos de São Gonçalo do Amarante (e seus distritos) poderão concorrer a vagas por esse portal.</li>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

usuario/templates/register_empregador.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}