candidato/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
#from .views import PretencoesAutocomplete
from .models import Profissoes, Pretencoes
from dal import autocomplete

app_name='candidato'    

urlpatterns = [
    path("info_basica", views.info_basica, name='info_basica'),
    path("formacao", views.formacao, name='formacao'),
    path("formacao/excluir-formacao/<id>", views.excluir_formacao, name='excluir_formacao'),
    path("formacao/editar-formacao/<id>", views.editar_formacao, name='editar_formacao'),
    path("experiencia", views.experiencia, name='experiencia'),
    path("experiencia/excluir-experiencia/<id>", views.excluir_experiencia, name='excluir_experiencia'),
    path("experiencia/editar-experiencia/<id>", views.editar_experiencia, name='editar_experiencia'),
    path("curso", views.curso, name='curso'),
    path("curso/excluir-curso/<id>", views.excluir_curso, name='excluir_curso'),
    path("curso/editar-curso/<id>", views.editar_curso, name='editar_curso'),
    path("idioma", views.idioma, name='idioma'),
    path("idioma/excluir-idioma/<id>", views.excluir_idioma, name='excluir_idioma'),
    path("idioma/editar-idioma/<id>", views.editar_idioma, name='editar_idioma'),
    path("pretencoes", views.pretencoes, name='pretencoes'),
    path("idioma/excluir-pretencao/<id>", views.excluir_pretencao, name='excluir_pretencao'),
    path("idioma/editar-pretencao/<id>", views.editar_pretencao, name='editar_pretencao'),
    #path("ocupacao-autocomplete", views.PretencoesAutocomplete, name='ocupacao_autocomplete'),
    path('ocupacao-autocomplete',autocomplete.Select2QuerySetView.as_view(model=Profissoes), name='select2_fk'),
    path("minhas-candidaturas", views.minhas_candidaturas, name='minhas_candidaturas'),
    path("minhas-candidaturas/excluir-candidatura/<id>", views.excluir_candidatura, name='excluir_candidatura'),
]

ciesga_currilos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings	
from django.conf.urls.static import static
from core import urls

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('candidato/', include('candidato.urls', namespace="candidato")),
    path('empregador/', include('empregador.urls', namespace="empregador")),
    path('vagas/', include('vagas.urls', namespace="vagas")),
    path('captcha/', include('captcha.urls')),
    
    
    #path('municipios_app/', include('municipios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path("", views.home, name='home'),
    path('contato', views.contact, name='contact'),
    path('saiba-mais', views.saiba_mais, name='saiba_mais')
]

usuario/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name='usuario'

urlpatterns = [
    path("password_reset", views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<key>', views.password_reset_confirm, 
        name='password_reset_confirm'),
    path('editar-senha/', views.edit_password,  name='edit_password'),
    path('login/', LoginView.as_view(template_name = 'login.html'), 
    	 name='login'),
    path('logout/', LogoutView.as_view(next_page= 'core:home'), 
    	 name='logout'),
    path('cadastre-se_candidato/', views.register, name='register'),
    path('cadastre-se_empregador/', views.register_empregador, name='register_empregador'),
    path('painel/', views.dashboard, name='dashboard'),
    path('teste/', views.choice_register, name='choice_register'),
]

usuario/models.py
from django.db import models
import re
import datetime
from django.core import validators
from django.conf import settings
from core.choices import *
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.contrib.auth.validators import UnicodeUsernameValidator

class User(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        'Usuário', max_length=30, unique=True, validators=[username_validator],
    )
    name = models.CharField('Nome Completo', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    user_type = models.CharField( 
    		'Tipo de Usuário',
			max_length=25,
			blank=False,
			choices=USER_TYPE,
		)			
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuario',
        #related_name='resets',
        on_delete=models.CASCADE,
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User
from candidato.models import *
from empregador.models import *

from core.utils import generate_hash_key
from core.mail import send_mail_template

from .models import PasswordReset
from django.contrib.localflavor.br.forms import BRCPFField,BRCNPJField
#from captcha.fields import CaptchaField


User = get_user_model()


class RegisterForm(forms.ModelForm):

    cpf = BRCPFField(label = 'CPF',max_length = 14 , min_length = 11)
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )
    #captcha = CaptchaField()
    
    def clean_cpf(self):
        cpf=self.cleaned_data['cpf']
        if Candidato.objects.filter(cpf=cpf).exists():
            raise forms.ValidationError('CPF já cadastrado')
        return cpf

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):    
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.user_type = "Candidato"
        if commit:
            user.save()
            candidato = Candidato()
            candidato.user_id = user.id
            candidato.cpf = self.cleaned_data['cpf']
            candidato.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

class Register_EmpregadorForm(forms.ModelForm):

    cnpj = BRCNPJField(label = 'CNPJ',max_length = 18 , min_length = 14)
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )
    #captcha = CaptchaField()
    
    def clean_cpf(self):
        cpf=self.cleaned_data['cpf']
        if Candidato.objects.filter(cpf=cpf).exists():
            raise forms.ValidationError('CPF já cadastrado')
        return cpf

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):    
        user = super(Register_EmpregadorForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.user_type = "Empregador"
        if commit:
            user.save()
            empregado = Empregador()
            empregado.user_id = user.id
            empregado.cnpj = self.cleaned_data['cnpj']
            empregado.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

        
class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário encontrado com este e-mail'
        )

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'password_reset_mail.html'
        subject = 'Criar nova senha no Portal CIESGA'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

class UserForm(forms.ModelForm):
    
    class Meta: 
        model = User
        fields = ['username', 'email', 'name', 'user_type','is_active', 'is_staff']

usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm,
    SetPasswordForm)
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages

from core.utils import generate_hash_key

from .forms import RegisterForm, PasswordResetForm, Register_EmpregadorForm
from .models import PasswordReset, User

User = get_user_model()

# Create your views here.
def register(request):
    template_name = 'register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('usuario:dashboard')
    else:
        form = RegisterForm()

    context = {
        'form': form,

    }
    return render(request, template_name, context)

def register_empregador(request):
    template_name = 'register_empregador.html'
    context = {}
    if request.method == 'POST':
        form = Register_EmpregadorForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('usuario:dashboard')
    else:
        form = Register_EmpregadorForm()

    context = {
        'form': form,

    }
    return render(request, template_name, context)

    
def password_reset(request):
    template_name = 'password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def dashboard(request):
    
    user=request.user 
    if user.user_type == 'Candidato':
        template_name = 'dashboard_candidato.html'
        context = {}
        return render(request, template_name, context)
    else :
        template_name = 'dashboard_empregador.html'
        context = {}
        return render(request, template_name, context)


@login_required
def edit_password(request):

    user = request.user
    if user.user_type == 'Candidato':
        template_name = 'edit_password.html'
    else:
        template_name = 'edit_password_empregador.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

def choice_register(request):
   return render(request, 'choice_register.html')

usuario/templates/templatetags/cursos_tag.html
         {% for curso in cursos %}
        <div class="well4">
          <div class='row'>
            <div class='col-xs-10'>
              <div class='col-xs-10'>
            <h2>
           {% if curso.data_saida == NULL %}
           {{ curso }} - {{ curos.instituicao }} - EM ANDAMENTO
           {% else %}
           {{ curso }} - {{ curso.instituicao }} - CONCLUÍDO
           {% endif %}
           </h2>
          <div class="pure-controls">
          <a href="{% url 'candidato:editar_curso' curso.id %}" 
          class="pure-button-primary primary-button">Editar</a>
           <a href="{% url 'candidato:excluir_curso' curso.id %}" 
           class="pure-button button-error">Excluir</a>
          </div>
            </div>
          </div>
        </div>
      </div>
           {% empty %}
            <aside-2 class="pure-u-1">
                <p>Nenhum curso adicionado</p>
            </aside-2>
          {% endfor %}

usuario/templates/templatetags/experiencia_tag.html
          {% for experiencia in experiencias %}
        <div class="well4">
          <div class='row'>
            <div class='col-xs-10'>
              <div class='col-xs-10'>
            <h2>
           {% if experiencia.data_saida == NULL %}
           {{ experiencia }} - {{ experiencia.empresa }} - EM ATIVIDADE
           {% else %}
           {{ experiencia }} - {{ experiencia.empresa }}
           {% endif %}
           </h2>
          <div class="pure-controls">
          <a href="{% url 'candidato:editar_experiencia' experiencia.id %}" 
          class="pure-button-primary primary-button">Editar</a>
           <a href="{% url 'candidato:excluir_experiencia' experiencia.id %}" 
           class="pure-button button-error">Excluir</a>
          </div>
            </div>
          </div>
        </div>
      </div>
           {% empty %}
            <aside-2 class="pure-u-1">
                <p>Nenhuma experiência adicionada</p>
            </aside-2>
          {% endfor %}

usuario/templates/templatetags/formacoes_tag.html
          {% for formacao in formacoes %}
        <div class="well4">
          <div class='row'>
            <div class='col-xs-10'>
              <div class='col-xs-10'>
            <h2>
           {% if formacao.data_conclusao == NULL %}
           {{ formacao }} - {{ formacao.instituicao }} - EM ANDAMENTO
           {% else %}
           {{ formacao }} - {{ formacao.instituicao }} - CONCLUÍDO
           {% endif %}
           </h2>
            <div class="pure-controls">
             <a href="{% url 'candidato:editar_formacao' formacao.id %}" 
              class="pure-button-primary primary-button">Editar</a>
             <a href="{% url 'candidato:excluir_formacao' formacao.id  %}" 
               class="pure-button button-error">Excluir
             </a>
                </div>
            </div>
            </div>
          </div>
        </div>
   			  {% empty %}
            <aside-2 class="pure-u-1">
                <p>Nenhuma formação adicionada</p>
            </aside-2>
          	{% endfor %}

      
        

usuario/templates/templatetags/idioma_tag.html
          {% for idioma in idiomas %}
        <div class="well4">
          <div class='row'>
            <div class='col-xs-10'>
              <div class='col-xs-10'>
            <h2>
           {{ idioma }} - {{ idioma.nivel }} 
           </h2>
            <div class="pure-controls">
              <a href="{% url 'candidato:editar_idioma' idioma.id %}" 
              class="pure-button-primary primary-button">Editar</a>
              <a href="{% url 'candidato:excluir_idioma' idioma.id  %}" 
               class="pure-button button-error">Excluir
              </a>
                </div>
            </div>
            </div>
          </div>
        </div>
   			  {% empty %}
            <aside-2 class="pure-u-1">
                <p>Nenhum idioma adicionado</p>
            </aside-2>
          	{% endfor %}

usuario/templates/templatetags/pretencoes_tag.html
         {% for pretencao in pretencoes %}
        <div class="well4">
          <div class='row'>
            <div class='col-xs-10'>
              <div class='col-xs-10'>
            <h2>
           {{ pretencao.profissao }} 
           </h2>
          <div class="pure-controls">
          <a href="{% url 'candidato:editar_pretencao' pretencao.id %}" 
          class="pure-button-primary primary-button">Editar</a>
           <a href="{% url 'candidato:excluir_pretencao' pretencao.id %}" 
           class="pure-button button-error">Excluir</a>
          </div>
            </div>
          </div>
        </div>
      </div>
           {% empty %}
            <aside-2 class="pure-u-1">
                <p>Nenhuma pretenção adicionada</p>
            </aside-2>
          {% endfor %}

usuario/templates/templatetags/register_empregador.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}