candidato/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
#from .views import PretencoesAutocomplete
from .models import Profissoes, Pretencoes
from dal import autocomplete

app_name='candidato'    

urlpatterns = [
    path("info_basica", views.info_basica, name='info_basica'),
    path("formacao", views.formacao, name='formacao'),
    path("formacao/excluir-formacao/<id>", views.excluir_formacao, name='excluir_formacao'),
    path("formacao/editar-formacao/<id>", views.editar_formacao, name='editar_formacao'),
    path("experiencia", views.experiencia, name='experiencia'),
    path("experiencia/excluir-experiencia/<id>", views.excluir_experiencia, name='excluir_experiencia'),
    path("experiencia/editar-experiencia/<id>", views.editar_experiencia, name='editar_experiencia'),
    path("curso", views.curso, name='curso'),
    path("curso/excluir-curso/<id>", views.excluir_curso, name='excluir_curso'),
    path("curso/editar-curso/<id>", views.editar_curso, name='editar_curso'),
    path("idioma", views.idioma, name='idioma'),
    path("idioma/excluir-idioma/<id>", views.excluir_idioma, name='excluir_idioma'),
    path("idioma/editar-idioma/<id>", views.editar_idioma, name='editar_idioma'),
    path("pretencoes", views.pretencoes, name='pretencoes'),
    path("idioma/excluir-pretencao/<id>", views.excluir_pretencao, name='excluir_pretencao'),
    path("idioma/editar-pretencao/<id>", views.editar_pretencao, name='editar_pretencao'),
    #path("ocupacao-autocomplete", views.PretencoesAutocomplete, name='ocupacao_autocomplete'),
    path('ocupacao-autocomplete',autocomplete.Select2QuerySetView.as_view(model=Profissoes), name='select2_fk'),
    path("minhas-candidaturas", views.minhas_candidaturas, name='minhas_candidaturas'),
    path("minhas-candidaturas/excluir-candidatura/<id>", views.excluir_candidatura, name='excluir_candidatura'),
]

ciesga_currilos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings	
from django.conf.urls.static import static
from core import urls

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('candidato/', include('candidato.urls', namespace="candidato")),
    path('empregador/', include('empregador.urls', namespace="empregador")),
    path('vagas/', include('vagas.urls', namespace="vagas")),
    path('captcha/', include('captcha.urls')),
    
    
    #path('municipios_app/', include('municipios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path("", views.home, name='home'),
    path('contato', views.contact, name='contact'),
    path('saiba-mais', views.saiba_mais, name='saiba_mais')
]

empregador/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='empregador'

urlpatterns = [
    path("info-basica", views.info_basica2, name='info_basica2'),
    path("cadastrar-vaga", views.cadastrar_vaga, name='cadastrar_vaga'),
    path("minhas-vagas", views.minhas_vagas, name='minhas_vagas'),
    path("minhas-vagas/excluir-vagas/<id>", views.excluir_vaga, name='excluir_vaga'),
    path("minhas-vagas/editar-vaga/<id>", views.editar_vaga, name='editar_vaga'),
    path("minhas-vagas/status-vagas/<id>", views.status_vaga, name='status_vaga'),
    path("minhas-vagas/ver-inscritos/<id>/", views.ver_inscritos, name='ver_inscritos'),
    path("minhas-vagas/ver-inscritos/detalhes/<id>", views.detalhes_candidato, name='detalhes_candidato'),
]

vagas/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='vagas'

urlpatterns = [
    path("mural-de-vagas/", views.mural_de_vagas, name='mural_de_vagas'),
    path("mural-de-vagas/ver-vaga/<id>", views.requisitos, name='requisitos'),
    path("mural-de-vagas/ver-vaga/inscricao/<id>", views.inscricao, name='inscricao'),
    ]

vagas/models.py
from django.db import models
from usuario.models import User
from candidato.models import Candidato
from empregador.models import Empregador 
from core.choices import *

# Create your models here.

class Vaga (models.Model):

	empregador = models.ForeignKey(Empregador, related_name='empregador', on_delete=models.CASCADE) 
	funcao = models.CharField ('Função', max_length = 50)
	descricao = models.TextField ('Descrição das Atividades', max_length = 1000, blank = False)
	confidencial = models.BooleanField ('Confidencial', default=False)
	data_criacao = models.DateTimeField('Data de Criação', auto_now_add=True)
	ultima_modificacao = models.DateTimeField('Última Modificação', auto_now_add=False, auto_now=True)
	status = models.BooleanField ('Está ativa?', blank=True, default=True)
	finalizada = models.BooleanField ('Foi finalizada?', blank=True, default=False)
	inscritos = models.PositiveSmallIntegerField ('Quantidade de inscritos', blank=True, null=True)
	salario = models.CharField ('Salário', max_length = 20, blank=True, null=True)
	local = models.CharField ('Cidade', max_length = 50)
	escolaridade = models.CharField(
			'Escolaridade exigida',
			max_length=25,
			null=True,
			blank=True,
			choices=EDUCATION_CHOICES,
		)
	

	def __str__(self):
		return self.funcao

	def get_vaga_detail_url(self):
		return u"/vagas/%i" % self.id

class Requisitos (models.Model):

	vaga = models.ForeignKey(Vaga, related_name='vaga_requisito', on_delete=models.CASCADE)
	requisito = models.TextField('Requisito', max_length=300)

	def __str__(self):
		return self.requisito

class Candidatura (models.Model):

	candidato =  models.ForeignKey(Candidato, related_name='candiato', on_delete=models.CASCADE)
	vaga = models.ForeignKey(Vaga, related_name='vaga', on_delete=models.CASCADE)
	#data_inscricao = models.DateTimeField('Data da Inscrição', auto_now_add=True)

	def __str__(self):
		return self.candidato.user.name

vagas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import *

User = get_user_model()

# Create your views here.

@login_required

def mural_de_vagas(request):
	vagas_list = Vaga.objects.filter(status = True, finalizada = False).order_by('-data_criacao')
	var_get_search = request.GET.get('search_box', None)
	if var_get_search:
		vagas_list = Vaga.objects.filter(status = True, finalizada = False, funcao__icontains=var_get_search).order_by('-data_criacao')
	paginator = Paginator(vagas_list, 15)


	try:
		page = (request.GET.get('page', '1'))
	except ValueError:
		page = 1
	try:
		vagas = paginator.page(page)
	except (EmptyPage, InvalidPage):
		vagas = paginator.page(1)

	index = vagas.number - 1
	max_index = len(paginator.page_range)
	start_index = index - 3 if index >= 3 else 0
	end_index = index + 3 if index <= max_index - 3 else max_index
	page_range = paginator.page_range[start_index:end_index]

	template_name = 'mural_de_vagas.html'
	return render(request, template_name,{ 
        'vagas': vagas,
        'page_range': page_range,
        })

@login_required

def requisitos(request, id):
	template_name = 'vaga.html'
	vaga = Vaga.objects.get(id=id)
	requisitos = Requisitos.objects.filter(vaga_id = id)
	context = {
            'vaga':vaga,
            'requisitos':requisitos,
        }
	return render(request, template_name, context)
	
@login_required

def inscricao(request, id):
	template_name = 'mural_de_vagas.html'
	vaga = Vaga.objects.get(id=id)
	user=request.user 

	if user.user_type == "Candidato":
		candidato = user.candidato
		tag = 0 
		tag2 = 0

		if candidato.escolaridade  == 'Fundamental incompleto':
			tag = 1
		elif candidato.escolaridade == 'Fundamental completo':
			tag = 2
		elif candidato.escolaridade == 'Medio incompleto':
			tag = 3
		elif candidato.escolaridade == 'Medio completo':
			tag = 4
		elif candidato.escolaridade == 'Tecnico incompleto':
			tag = 5
		elif candidato.escolaridade == 'Tecnico completo':
			tag = 6
		elif candidato.escolaridade == 'Superior incompleto':
			tag = 7
		elif candidato.escolaridade == 'Superior completo':
			tag = 8
		elif candidato.escolaridade == 'Pos-Graduacao':
			tag = 9
		elif candidato.escolaridade == 'Mestrado':
			tag = 10
		elif candidato.escolaridade == 'Doutorado':
			tag = 11
		else:
			tag = 12

		if vaga.escolaridade == 'Fundamental incompleto' or vaga.escolaridade == '':
			tag2 = 1
		elif vaga.escolaridade == 'Fundamental completo':
			tag2 = 2
		elif vaga.escolaridade == 'Medio incompleto':
			tag2 = 3
		elif vaga.escolaridade == 'Medio completo':
			tag2 = 4
		elif vaga.escolaridade == 'Tecnico incompleto':
			tag2 = 5
		elif vaga.escolaridade == 'Tecnico completo':
			tag2 = 6
		elif vaga.escolaridade == 'Superior incompleto':
			tag2 = 7
		elif vaga.escolaridade == 'Superior completo':
			tag2 = 8
		elif vaga.escolaridade == 'Pos-Graduacao':
			tag2 = 9
		elif vaga.escolaridade == 'Mestrado':
			tag2 = 10
		elif vaga.escolaridade == 'Doutorado':
			tag2 = 11
		else:
			tag2 = 12

		if candidato.escolaridade == None:
			messages.info(
		                request, 'Inscrição não realizada. Preencha suas informações básicas para poder candidatar-se as vagas.'
		            )

		elif tag >= tag2:
		 	inscricao, criado = Candidatura.objects.get_or_create(candidato = candidato, vaga = vaga)
		 	if  criado:
		 		messages.success(
		                request, 'A sua inscrição foi realizada com sucesso.'
		            )
		 	else:
		 		messages.success(
		                request, 'Você já se cadastrou nessa vaga. Acompanhe suas candidaturas pelo Painel.'
		            )
		else:
			messages.success(
		                request, 'Você não possui a escolaridade mínima exigida para essa vaga.'
		            )

		return redirect('vagas:mural_de_vagas')
	else:
		messages.info(
	                request, 'Apenas usuários do tipo candidato podem se candidatar em vagas de emprego.'
	            )
		return redirect('vagas:mural_de_vagas')

vagas/templates/templatetags/minhas_candidaturas_tag.html
{% for candidatura in tag %}
<div class="well4" id='{{ vaga.id }}'>
        <div class='row'>
          <div class='col-xs-10'>
            <div class='col-xs-10'>
              <h1 class="splash-head">
              {{ candidatura.vaga.funcao }}
              </h1>
            </div>
            <div class='col-xs-8'>
              <ul class="list-inline">
                <li>Local: {{ candidatura.vaga.local }}</li>
                {% if candidatura.vaga.confidencial == True %}
                <li>Empresa: Confidencial </li>
                {% else %}
                <li>Empresa: {{ candidatura.vaga.empregador.nome }}</li>
                {% endif %}
                <li>Criado: {{ candidatura.vaga.data_criacao | date:"d M Y"}}</li>
              </ul>
            </div>
            <div class='col-xs-4'>
              <a href="{% url 'candidato:excluir_candidatura' candidatura.id %}" class="pure-button button-error" role="button"> Cancelar Inscrição</a>

            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="pure-u-1 text-center">
          <h3>Você não possui candidaturas ativas</h3>
      </div>

{% endfor %}

vagas/templates/templatetags/minhas_vagas_tag.html
{% for vaga in vagas %}
<div class="well4" id='{{ vaga.id }}'>
        <div class='row'>
          <div class='col-xs-10'>
            <div class='col-xs-10'>
              <h1 class="splash-head">
              {{ vaga.funcao }}
              </h1>
            </div>
            <div class='col-xs-8'>
              <ul class="list-inline">
                <li>Local: {{ vaga.local }}</li>
                {% if vaga.confidencial == True %}
                <li>Empresa: Confidencial </li>
                {% else %}
                <li>Empresa: {{ vaga.empregador.nome }}</li>
                {% endif %}
                <li>Criado: {{ vaga.data_criacao | date:"d M Y"}}</li>
              </ul>
            </div>
            <div class='col-xs-4'>
              <a href="{% url 'empregador:ver_inscritos' vaga.id %}" class="pure-button button-success" role="button">Ver inscritos</a>
              {% if vaga.status %}
              <a href="{% url 'empregador:status_vaga' vaga.id %}" class="pure-button button-warning" role="button">Encerrar</a>
              {% else %}
              <a href="{% url 'empregador:status_vaga' vaga.id %}" class="pure-button-primary" role="button"> Ativar</a>
              {% endif %}
              <a href="{% url 'empregador:editar_vaga' vaga.id %}" class="pure-button button-secondary" role="button">Editar</a>
              <a href="{% url 'empregador:excluir_vaga' vaga.id %}" class="pure-button button-error" role="button">Excluir</a>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="pure-u-1 text-center">
          <h3>Você ainda não cadastrou nenhuma vaga</h3>
      </div>

{% endfor %}

vagas/templates/templatetags/vaga_tag.html
    {% for vaga in vagas %}
    <div class="well3" id='{{ vaga.id }}'>
            <div class='row'>
              <div class='col-xs-10'>
                <div class='col-xs-10'>
                  <h1 class="splash-head">
                    Emprego para {{ vaga.funcao }}
                  </h1>
                </div>
                <div class='col-xs-8'>
                  <ul class="list-inline">
                    <li>Local: {{ vaga.local }}</li>
                    {% if vaga.confidencial == True %}
                    <li>Empresa: Confidencial </li>
                    {% else %}
                    <li>Empresa: {{ vaga.empregador.nome }}</li>
                    {% endif %}
                    {% if vaga.escolaridade == '' %}
                    <li>Escolaridade Exigida: Nenhuma </li>
                    {% else %}
                    <li>Escolaridade Exigida: {{ vaga.escolaridade }} </li>
                    {% endif %}
                    <li>Criado: {{ vaga.data_criacao | date:"d M Y"}}</li>
                  </ul>
                </div>
                <div class='col-xs-4 text-center'>
                  <a href="{% url 'vagas:requisitos' vaga.id %}" class="pure-button-primary primary-button" role="button">Ver Vaga</a>
                </div>
              </div>
            </div>
          </div>
          {% empty %}
          <div class="pure-u-1 text-center">
              <h3>Não temos nenhuma vaga cadastrada no momento</h3>
          </div>
    {% endfor %}

     <center class="pagination">
            <ul class="pagination">
            <span class="step-links">
            {% if vagas.has_previous %}
                <a id="prev" href="?page={{ vagas.previous_page_number }}">&laquo;</a>&emsp;
            {% else %}
                    <class="disabled"><span>&laquo;</span>&emsp;
            {% endif %}

            <span class="current">
                {% for i in page_range %}
                    {% if vagas.number == i %}
                            <a class= "home-menu" href="?page={{ i }}">{{ i }}
                                <span class="sr-only"></span>
                            </a>  &emsp;
                    {% else %}
                            <a href="?page={{ i }}">
                                {{ i }} 
                            </a>  &emsp;
                    {% endif %}
                {% endfor %}
            </span>

            {% if vagas.has_next %}
                <a id="next" href="?page={{ vagas.next_page_number }}">&raquo;</a>
            {% else %}
               <class="disabled"><span>&raquo;</span>
            {% endif %}
          </ul>
    }
    }
    </center>