ciesga_currilos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings	
from django.conf.urls.static import static
from core import urls

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('candidato/', include('candidato.urls', namespace="candidato")),
    path('empregador/', include('empregador.urls', namespace="empregador")),
    path('vagas/', include('vagas.urls', namespace="vagas")),
    path('captcha/', include('captcha.urls')),
    
    
    #path('municipios_app/', include('municipios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path("", views.home, name='home'),
    path('contato', views.contact, name='contact'),
    path('saiba-mais', views.saiba_mais, name='saiba_mais')
]

usuario/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name='usuario'

urlpatterns = [
    path("password_reset", views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<key>', views.password_reset_confirm, 
        name='password_reset_confirm'),
    path('editar-senha/', views.edit_password,  name='edit_password'),
    path('login/', LoginView.as_view(template_name = 'login.html'), 
    	 name='login'),
    path('logout/', LogoutView.as_view(next_page= 'core:home'), 
    	 name='logout'),
    path('cadastre-se_candidato/', views.register, name='register'),
    path('cadastre-se_empregador/', views.register_empregador, name='register_empregador'),
    path('painel/', views.dashboard, name='dashboard'),
    path('teste/', views.choice_register, name='choice_register'),
]

vagas/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name='vagas'

urlpatterns = [
    path("mural-de-vagas/", views.mural_de_vagas, name='mural_de_vagas'),
    path("mural-de-vagas/ver-vaga/<id>", views.requisitos, name='requisitos'),
    path("mural-de-vagas/ver-vaga/inscricao/<id>", views.inscricao, name='inscricao'),
    ]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from .mail import send_mail_template


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    subject = forms.CharField(label='Assunto', max_length=100)
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'subject': self.cleaned_data['subject'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'core/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

core/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'home.html')


def saiba_mais(request):
    return render(request, 'saiba_mais.html')

def contact(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form = ContactForm()
    else:
        form = ContactForm()
    context['form'] = form
    template_name = 'contact.html'
    return render(request, template_name, context)

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Portal CIESGA - Uma simples plataforma de apoio ao trabalhador" />
    <title>Portal CIESGA</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
        
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">Portal CIESGA</a>
        <ul>
            {% if user.is_authenticated %}
            Bem-vindo(a),
                <strong>{{ user.username }}</strong>.
            {% endif %}
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'vagas:mural_de_vagas' %}">Vagas</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'usuario:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'usuario:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'usuario:login' %}">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
       Copyright &copy;  Portal CIESGA
    </div>
</div>
	<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale conosco</h1>
        <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="">desenvolvimento@saogoncalo.rn.gov.br</a></li>
            <li>Telefone: <a href="">(84) 99105-3276</a></li>
             <li>Facebook: <a href=""></a></li>
            <li>Endereço: <a href="">Av Engenheiro Roberto Freire – Nº1000 / Santo Antônio do Potengi - RN</a></li>
        </ul>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Dúvidas/Sugestões</h1>
        {% if is_valid %}
        <p>Sua mensagem foi enviada com sucesso. Obrigado por falar conosco</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

core/templates/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

core/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Uma Plataforma de apoio ao trabalhador de SGA-RN
                </h1>
                <h2 class="splash-subhead">
                    O Portal CIESGA realiza intermediação entre empresas que precisam de mão de obra e profissionais que procuram emprego de forma totalmente transparente.
                </h2>
                <p>
                    <a href="{% url 'core:saiba_mais' %}" class="pure-button-primary primary-button">Saiba mais</a>
                    <a href="{% url 'usuario:choice_register' %}" class="pure-button-primary secundary-button">Cadastre-se</a>
                </p>
            </div>
        </div> 
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Banco de currículos</h4>
            <h3>Registre seu currículo</h3>
            <p>
                O Portal CIESGA tem um sistema simples e prático para que o trabalhador de São Gonçalo do Amarante divulgue seu currículo e concorra a vagas de emprego que nossa cidade disponibiliza.
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Banco de currículos.">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Catálogo de vagas">
        </div>
    </div>  
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Catálogo de vagas</h4>
            <h3>Encontre a vaga com seu perfil</h3>
            <p>
                No Portal CIESGA você pode consultar as vagas de trabalho que estão disponíveis e candidatar-se.
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Empregador</h4>
            <h3>Crie vagas e tenha acesso ao nosso banco de currículos</h3>
            <p>
                Você pode divulgar vagas de empregos (anonimamente ou não) em nosso portal e ter acesso ao nosso completo banco de currículos para selecionar o melhor profissional para o sua empresa.
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'image/4.png' %}"
                 alt="Empregador">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'image/6.jpg' %}"
                 alt="Cursos">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Cursos (EM BREVE)</h4>
            <h3>Se inscreva em cursos através do nosso portal</h3>
            <p>
                Em breve o Portal CIESGA disponibilizará inscrições em cursos presenciais e online para manter você sempre praparado para o mercado de trabalho.
            </p>
        </div>
    </div>
</div>
{% endblock %}

core/templates/saiba_mais.html
{% extends "base.html" %}
{% block content %}

<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Uma Plataforma de apoio ao trabalhador de SGA-RN
                </h1>
                <h2 class="splash-subhead">
                    O Portal CIESGA realiza intermediação entre empresas que precisam de mão de obra e profissionais que procuram emprego de forma totalmente transparente.

                </h2>
                <p>
                    <a href="{% url 'core:home' %}" class="pure-button-primary primary-button">Início</a>
                    <a href="{% url 'usuario:choice_register' %}" class="pure-button-primary secundary-button">Cadastre-se</a>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="pure-g-r content-ribbon">
    <div class="pure-u">
        <div class="l-box">
        	<h4 class="content-subhead">Portal CIESGA</h4>
        	   	<pre class="pure-u" align="justify">
	Com esta ferramenta pretendemos tornar o processo de encontrar uma vaga de emprego muito mais fácil e transparente, tanto para o cidadão quanto para a empresa que precisa de mão de obra. A Prefeitura de São Gonçalo do Amarante tem colocado seus esforços em trazer novas oportunidades e abrir novas vagas aqui mesmo no município, para que seus moradores não tenham que se deslocar para outras cidades em busca de emprego.<br>
	Aqui o cidadão fará seu cadastro, com todas os seus dados, e informará suas áreas de interesse profissional. As empresas também farão seus cadastros e poderão disponibilizar vagas a serem preenchidas. Se o candidato for da área de interesse da empresa e atender seus requisitos, automaticamente estará concorrendo àquela vaga. Se não for, mesmo assim poderá tentar concorrer, obviamente não tendo tantas chances de conseguir preenchê-la. Além disso, candidatos e empresas poderão acompanhar vagas abertas, resumo de outros candidatos, quantidade de profissionais concorrendo a uma vaga, dentre outras funcionalidades.<br>
	Queremos que todos tenham certeza que estão sendo respeitados os critérios de seleção das empresas. Que a administração pública não interfere no processo, garantindo que candidatos às vagas de emprego no município estejam sendo aproveitados de acordo com suas capacidades profissionais. Além disso, através dos cadastros é possível avaliar a realidade do mercado de trabalho local e as necessidades de cursos de qualificação para a população.
			</pre>
		</div>
	</div>
</div>


{% endblock %}